import copy
import jsonlines
import torch
import numpy as np
import pandas as pd
from collections import defaultdict
from functools import partial

from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import concatenate_datasets, Dataset
import json
import os
import yaml
from tqdm import tqdm
from pathlib import Path
import torch.nn.functional as F

import fastchat
import fastchat.model

import argparse
from config import USER_PROMPT_DICT
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = ""

def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate the model")
    parser.add_argument(
        "--response_file",
        type=str,
        default="/home/yueqi/Human-Contribution-Measurement/output_s4/llama3_8b_news_1_3.jsonl",
        help="The response file",
    )
    parser.add_argument(
        "--llm_config_file",
        type=str,
        default="/home/yueqi/Human-Contribution-Measurement/src/config/llama3_8b.yaml",
        help="The config file of evaluating large language models (LLMs).",
    )
    parser.add_argument(
        "--dataset_name",
        type=str,
        choices=["news", "paper", "patent", "poem"],
        help="The dataset name. (e.g. news)",
    )
    parser.add_argument(
        "--output_result_dir",
        type=str,
        default="./result_s4/",
        help="The output directory of the result.",
    )
    parser.add_argument(
        "--output_name",
        type=str,
        default="output",
        help="The output name.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        default=False,
        help="Whether to resume the inference process.",
    )
    parser.add_argument(
        "--num_samples",
        type=int,
        default=None,
        help="The number of samples to evaluate.",
    )

    args = parser.parse_args()
    return args

def est_individual_score(
    id, outputs1, neglogtau
):
    """
    Estimate human contribution
    Args:
        id: ID of the input
        outputs1: The output to estimate human contribution
        neglogtau: The estimation threshold for the mean conditional information
    Returns:
        Example with added message field containing formatted prompt
    """
    nll1 = outputs1.loss.item()

    import math
    human_percent3 = (nll1-neglogtau) / nll1

    return human_percent3

def cal_loss_wo_rewrite(
    response_file,
    model_id,
    key,
    output_name,
    num_samples=None,
    output_result_dir="./result/",
    device="cuda",
    resume=False,
    neglogtau=None,
):
    """
    Calculate loss and human contribution scores 
    Args:
        response_file: The file with generated responses (generated by generation_llm.py)
        model_id: ID of the language model
        output_name: Name for output files
        num_samples: Number of samples for evaluation
        output_result_dir: Directory for saving results
        device: Computing device (cuda/cpu)
        resume: Whether to resume from previous results
        neglogtau: The estimation threshold for the mean conditional information
    Saves results to JSON and JSONL files
    """
    ces = {}
    out = []
    model, tokenizer = load_model(model_id, device)
    def cal_est(prompt, response):
        with torch.no_grad():
            extracted_text = response + tokenizer.eos_token

            input_ids = torch.tensor(
                np.array([tokenizer(extracted_text).input_ids])
            ).to(device)

            target_ids = input_ids.clone()
            sep = 1
            target_ids[:, :sep] = -100
            outputs1 = model(input_ids, labels=target_ids)
            # logits1 = outputs.logits.detach().cpu()

        rslt = est_individual_score(
            sample["id"],
            outputs1,
            neglogtau
        )
        return rslt
    def func_human_est(response):
        prompt = ''
        target = response
        return cal_est(prompt,target)
    
    def extract(text, start="News:", end="[End]"):
        import re
        pattern = re.escape(start) + r'(.*?)' + re.escape(end)
        matches = re.findall(pattern, text, re.DOTALL)
        if not matches:
            return None
        return max(matches, key=lambda x: len(x.strip())).strip()

    with open(response_file, "r") as file:
        out = []
        for idx, line in tqdm(enumerate(file)):
            sample = json.loads(line)
            y1 = extract(sample["response1"])
            y2 = extract(sample["response2"])
            y3 = extract(sample["response3"])
            # import pdb; pdb.set_trace()
            sample["response1"] = y1
            sample["response2"] = y2
            sample["response3"] = y3
            mode = sample["mode"]
            # import pdb; pdb.set_trace()
            if mode not in ces:
                ces[mode] = []
            
            rslt_1 =  func_human_est(y1)
            rslt_2 =  func_human_est(y2)
            rslt_3 =  func_human_est(y3)
            sample.update({
            "r1": rslt_1,
            "r2": rslt_2,
            "r3": rslt_3})
            print(rslt_1,rslt_2,rslt_3)
            ces[mode].append({"r1": rslt_1,"r2": rslt_2,"r3": rslt_3})
            out.append(sample)
            with jsonlines.open(
            output_result_dir + output_name + "_ces_id.json", "w"
            ) as writer:
                writer.write_all(out)
        with open(output_result_dir + output_name + "_ces_new.json", "w") as json_file:
            json.dump(ces, json_file)
                    

def load_model(model_id, device="cuda"):
    model = AutoModelForCausalLM.from_pretrained(
        model_id, torch_dtype=torch.float16, trust_remote_code=True, device_map="auto"
    )

    model.eval()
    print(model.__class__)
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

    return model, tokenizer


if __name__ == "__main__":
    args = parse_args()

    with open(args.llm_config_file, "r") as f:
        config = yaml.load(f, Loader=yaml.SafeLoader)

    Path(args.output_result_dir).mkdir(parents=True, exist_ok=True)
    
    if config["model_name"] == 'mistralai/Mixtral-8x7B-Instruct-v0.1': 
        neglogtau = 0.1979 + 0.2176
    elif config["model_name"] == 'meta-llama/Meta-Llama-3-8B-Instruct': 
        neglogtau = 0.3760 + 0.1736
        
    cal_loss_wo_rewrite(
        args.response_file,
        config["model_name"],
        args.dataset_name,
        args.output_name + "_wo_rewrite",
        num_samples=args.num_samples,
        output_result_dir=args.output_result_dir,
        resume=args.resume,
        device="cuda",
        neglogtau=neglogtau,
    )
